//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OziBazaar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailConfiguration
    {
        public EmailConfiguration()
        {
            this.EmailAudits = new HashSet<EmailAudit>();
        }
    
        public int EmailConfigurationID { get; set; }
        public string Description { get; set; }
        public string TemplatePath { get; set; }
        public Nullable<int> EmailTypeID { get; set; }
        public string Subject { get; set; }
        public byte[] Version { get; set; }
    
        public virtual ICollection<EmailAudit> EmailAudits { get; set; }
        public virtual EmailType EmailType { get; set; }
    }
}
