//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OziBazaar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTemplate
    {
        public NotificationTemplate()
        {
            this.NotificationAudits = new HashSet<NotificationAudit>();
        }
    
        public int NotificationTemplateID { get; set; }
        public string Description { get; set; }
        public string TemplatePath { get; set; }
        public Nullable<int> NotificationTypeID { get; set; }
        public string Subject { get; set; }
        public byte[] Version { get; set; }
    
        public virtual ICollection<NotificationAudit> NotificationAudits { get; set; }
        public virtual NotificationType NotificationType { get; set; }
    }
}
