//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OziBazaar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategoryHierarchy
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<short> LevelId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int HasChild { get; set; }
        public Nullable<int> EditorId { get; set; }
    }
}
